name: Nodejs App CI/CD.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t 2cloud .  

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Image to Docker Hub
      run: |
        docker tag 2cloud ${{ secrets.DOCKERHUB_USERNAME }}/2cloud:latest2
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/2cloud:latest2

